# I'm still not sure which info here is redundant
development:
  adapter: postgresql
  database: sinatra
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: circle_test
  host: localhost
  min_messages: WARNING