

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  min_messages: WARNING

development:
  <<: *default
  database: sinatra

test:
  <<: *default
  database: circle_test

production:
  <<: *default
  database: shirtly_api_production
  username: rails
  password: vZg0nqbvLz