

default: &default
  adapter: postgresql
  host: localhost
  min_messages: WARNING

development:
  <<: *default
  database: sinatra

test:
  <<: *default
  database: circle_test

production:
  <<: *default
  database: shirtly_api
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>